import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { dehydrate, HydrationBoundary } from '@tanstack/react-query';

import Providers from './providers/providers';

import { userMeOptions } from '@/shared/api/generated/@tanstack/react-query.gen';
import { getQueryClient } from '@/shared/api/query-client';

import 'highlight.js/styles/atom-one-dark.css';
import './styles/globals.css';

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery(userMeOptions());
  return (
    <html lang='en'>
      <body className={`${robotoSans.variable} overflow-x-hidden`}>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            {children}
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
