// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthPassword struct {
	UserID       int32
	Login        string
	PasswordHash string
}

type Post struct {
	ID        int32
	ThreadID  int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	JwtID  pgtype.UUID
	UserID int32
}

type Thread struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	PostsCount int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
