// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authCreate = `-- name: AuthCreate :exec
INSERT INTO auth_passwords (user_id, login, password_hash) VALUES ($1, $2, $3)
`

type AuthCreateParams struct {
	UserID       int32
	Login        string
	PasswordHash string
}

func (q *Queries) AuthCreate(ctx context.Context, arg AuthCreateParams) error {
	_, err := q.db.Exec(ctx, authCreate, arg.UserID, arg.Login, arg.PasswordHash)
	return err
}

const authCreateSession = `-- name: AuthCreateSession :exec
INSERT INTO sessions (session_id, user_id) VALUES ($1, $2)
`

type AuthCreateSessionParams struct {
	SessionID pgtype.UUID
	UserID    int32
}

func (q *Queries) AuthCreateSession(ctx context.Context, arg AuthCreateSessionParams) error {
	_, err := q.db.Exec(ctx, authCreateSession, arg.SessionID, arg.UserID)
	return err
}

const authDeleteAllUserSessions = `-- name: AuthDeleteAllUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) AuthDeleteAllUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, authDeleteAllUserSessions, userID)
	return err
}

const authDeleteSession = `-- name: AuthDeleteSession :exec
DELETE FROM sessions WHERE session_id = $1
`

func (q *Queries) AuthDeleteSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authDeleteSession, sessionID)
	return err
}

const authGetUserAndPasswordHash = `-- name: AuthGetUserAndPasswordHash :one
SELECT user_id, password_hash FROM auth_passwords WHERE login = $1
`

type AuthGetUserAndPasswordHashRow struct {
	UserID       int32
	PasswordHash string
}

func (q *Queries) AuthGetUserAndPasswordHash(ctx context.Context, login string) (AuthGetUserAndPasswordHashRow, error) {
	row := q.db.QueryRow(ctx, authGetUserAndPasswordHash, login)
	var i AuthGetUserAndPasswordHashRow
	err := row.Scan(&i.UserID, &i.PasswordHash)
	return i, err
}

const authGetUserIDBySessionID = `-- name: AuthGetUserIDBySessionID :one
SELECT user_id FROM sessions WHERE session_id = $1
`

func (q *Queries) AuthGetUserIDBySessionID(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, authGetUserIDBySessionID, sessionID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const authUpdatePassword = `-- name: AuthUpdatePassword :exec
UPDATE auth_passwords SET password_hash = $2 WHERE user_id = $1
`

type AuthUpdatePasswordParams struct {
	UserID       int32
	PasswordHash string
}

func (q *Queries) AuthUpdatePassword(ctx context.Context, arg AuthUpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, authUpdatePassword, arg.UserID, arg.PasswordHash)
	return err
}

const postCreate = `-- name: PostCreate :one
INSERT INTO posts (thread_id, user_id, content) VALUES ($1, $2, $3)
RETURNING id, thread_id, user_id, content, created_at
`

type PostCreateParams struct {
	ThreadID int32
	UserID   int32
	Content  string
}

type PostCreateRow struct {
	ID        int32
	ThreadID  int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) PostCreate(ctx context.Context, arg PostCreateParams) (PostCreateRow, error) {
	row := q.db.QueryRow(ctx, postCreate, arg.ThreadID, arg.UserID, arg.Content)
	var i PostCreateRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const postListByThreadId = `-- name: PostListByThreadId :many
SELECT id, thread_id, user_id, content, created_at FROM posts
WHERE thread_id = $1 ORDER BY created_at DESC
`

type PostListByThreadIdRow struct {
	ID        int32
	ThreadID  int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) PostListByThreadId(ctx context.Context, threadID int32) ([]PostListByThreadIdRow, error) {
	rows, err := q.db.Query(ctx, postListByThreadId, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostListByThreadIdRow
	for rows.Next() {
		var i PostListByThreadIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadCreate = `-- name: ThreadCreate :one
INSERT INTO threads (title, content, user_id, posts_count) VALUES ($1, $2, $3, 1)
RETURNING id, title, content, posts_count, user_id, created_at
`

type ThreadCreateParams struct {
	Title   string
	Content string
	UserID  int32
}

type ThreadCreateRow struct {
	ID         int32
	Title      string
	Content    string
	PostsCount int32
	UserID     int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ThreadCreate(ctx context.Context, arg ThreadCreateParams) (ThreadCreateRow, error) {
	row := q.db.QueryRow(ctx, threadCreate, arg.Title, arg.Content, arg.UserID)
	var i ThreadCreateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.PostsCount,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const threadGetById = `-- name: ThreadGetById :one
SELECT id, title, content, user_id, posts_count, created_at FROM threads WHERE id = $1
`

type ThreadGetByIdRow struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	PostsCount int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ThreadGetById(ctx context.Context, id int32) (ThreadGetByIdRow, error) {
	row := q.db.QueryRow(ctx, threadGetById, id)
	var i ThreadGetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.PostsCount,
		&i.CreatedAt,
	)
	return i, err
}

const threadPageByPageID = `-- name: ThreadPageByPageID :many
SELECT id, title, content, user_id, posts_count, created_at
FROM threads
ORDER BY id DESC LIMIT $1 OFFSET $2
`

type ThreadPageByPageIDParams struct {
	Limit  int32
	Offset int32
}

type ThreadPageByPageIDRow struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	PostsCount int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ThreadPageByPageID(ctx context.Context, arg ThreadPageByPageIDParams) ([]ThreadPageByPageIDRow, error) {
	rows, err := q.db.Query(ctx, threadPageByPageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadPageByPageIDRow
	for rows.Next() {
		var i ThreadPageByPageIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.PostsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadPagesAfterThreadID = `-- name: ThreadPagesAfterThreadID :many
SELECT id, title, content, user_id, posts_count, created_at
FROM threads
WHERE id > $1
ORDER BY id DESC LIMIT $2
`

type ThreadPagesAfterThreadIDParams struct {
	ID    int32
	Limit int32
}

type ThreadPagesAfterThreadIDRow struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	PostsCount int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ThreadPagesAfterThreadID(ctx context.Context, arg ThreadPagesAfterThreadIDParams) ([]ThreadPagesAfterThreadIDRow, error) {
	rows, err := q.db.Query(ctx, threadPagesAfterThreadID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadPagesAfterThreadIDRow
	for rows.Next() {
		var i ThreadPagesAfterThreadIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.PostsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadPagesBeforeThreadID = `-- name: ThreadPagesBeforeThreadID :many
SELECT id, title, content, user_id, posts_count, created_at
FROM threads
WHERE id < $1
ORDER BY id DESC LIMIT $2
`

type ThreadPagesBeforeThreadIDParams struct {
	ID    int32
	Limit int32
}

type ThreadPagesBeforeThreadIDRow struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	PostsCount int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ThreadPagesBeforeThreadID(ctx context.Context, arg ThreadPagesBeforeThreadIDParams) ([]ThreadPagesBeforeThreadIDRow, error) {
	rows, err := q.db.Query(ctx, threadPagesBeforeThreadID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadPagesBeforeThreadIDRow
	for rows.Next() {
		var i ThreadPagesBeforeThreadIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.PostsCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCreate = `-- name: UserCreate :one
INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email
`

type UserCreateParams struct {
	Name  string
	Email string
}

type UserCreateRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (UserCreateRow, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Name, arg.Email)
	var i UserCreateRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const userGet = `-- name: UserGet :one
SELECT id, name, email FROM users WHERE id = $1
`

type UserGetRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) UserGet(ctx context.Context, id int32) (UserGetRow, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i UserGetRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const userGetByNameOrEmail = `-- name: UserGetByNameOrEmail :many
SELECT id, name, email FROM users WHERE name = $1 OR email = $2
`

type UserGetByNameOrEmailParams struct {
	Name  string
	Email string
}

type UserGetByNameOrEmailRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) UserGetByNameOrEmail(ctx context.Context, arg UserGetByNameOrEmailParams) ([]UserGetByNameOrEmailRow, error) {
	rows, err := q.db.Query(ctx, userGetByNameOrEmail, arg.Name, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGetByNameOrEmailRow
	for rows.Next() {
		var i UserGetByNameOrEmailRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userGetNameById = `-- name: UserGetNameById :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) UserGetNameById(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, userGetNameById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const userUpdate = `-- name: UserUpdate :one
UPDATE users
SET name = $1, email = $2
WHERE id = $3 RETURNING id, name, email
`

type UserUpdateParams struct {
	Name  string
	Email string
	ID    int32
}

type UserUpdateRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (UserUpdateRow, error) {
	row := q.db.QueryRow(ctx, userUpdate, arg.Name, arg.Email, arg.ID)
	var i UserUpdateRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
