# build:
# cd project_root; podman build -t comunicore:latest -f config/dev/Dockerfile.dev .
# run:
# cd project_root;
# podman run -it --rm -v./frontend/out:/var/www/html -p localhost:8080:80 comunicore:latest

# build comunicore backend
FROM golang:trixie AS backend

WORKDIR /app

COPY ./backend/go.mod ./backend/go.sum .
RUN go mod download

COPY ./backend .
RUN CGO_ENABLED=0 GOOS=linux go build -o comunicore ./cmd/forum; \
    CGO_ENABLED=0 GOOS=linux go build -o migrate ./cmd/migrate

# final image
FROM docker.io/library/postgres:18

WORKDIR /app
COPY --parents ./backend/internal/repository/./migrations ./backend/config/./server-config.toml .
COPY --from=backend --parents /app/./comunicore /app/./migrate .

# скрипт запуска nginx и бэкенда и базы данных
ENV FORUM_SERVER_JWTSECRET=supersecret \
    FORUM_DATABASE_PASSWORD=comunicore \
    POSTGRES_DB=comunicore \
    POSTGRES_USER=comunicore \
    POSTGRES_PASSWORD=comunicore

EXPOSE 8080
VOLUME /var/lib/postgresql /var/www/html

COPY ./config/dev/run_all.sh .

RUN apt update && apt install -y nginx netcat-openbsd; apt clean; rm -rf /var/lib/apt/lists/*
COPY ./config/dev/nginx-default-host.conf /etc/nginx/sites-available/default

CMD ["./run_all.sh"]
